const monstersActionTypes = {
  REQUEST_MONSTERS_PENDING: " REQUEST_MONSTERS_PENDING",
  REQUEST_MONSTERS_SUCCESS: "  REQUEST_MONSTERS_SUCCESS",
  REQUEST_MONSTERS_FAILED: " REQUEST_MONSTERS_FAILED"
};

export default monstersActionTypes;
