const monstersActionTypes = {
  REQUEST_MONSTERS_PENDING: " REQUEST_MONSTERS_PENDING",
  REQUEST_MONSTERS_SUCCESS: "  REQUEST_MONSTERS_SUCCESS",
  REQUEST_MONSTERS_FAILED: " REQUEST_MONSTERS_FAILED",
  FILTERED_MONSTERS: " FILTERED_MONSTERS",
  SEARCHFIELD_CHANGE: "SEARCHFIELD_CHANGE"
};

export default monstersActionTypes;
